image: alpine/latest
oauth: pages.sr.ht/PAGES:RW
sources:
- https://git.sr.ht/~sircmpwn/qbe
- https://git.sr.ht/~sircmpwn/harec
- https://git.sr.ht/~sircmpwn/hare
triggers:
  - action: email
    condition: failure
    to: ~sircmpwn/hare-dev@lists.sr.ht
tasks:
- qbe: |
    cd qbe
    make PREFIX=/usr
    sudo make install PREFIX=/usr
- harec: |
    mkdir harec/build
    cd harec/build
    ../configure --prefix=/usr
    make -j2
    sudo make install
- hare: |
    cd hare
    cp config.example.mk config.mk
    make
- tests: |
    cd hare
    make .bin/hare-tests
- check: |
    cd hare
    make check
- docs: |
    if [ $BUILD_SUBMITTER != "git.sr.ht" ]
    then
        echo "Skipping docs for non-git.sr.ht build"
        exit
    fi
    cd hare
    . hare.sh
    ./scripts/gen-docs
    tar -C docs/html -cvz . > docs.tar.gz
    acurl -f https://pages.sr.ht/publish/docs.harelang.org -Fcontent=@docs.tar.gz
